services:
  spatial-memory-game:
    image: houndmediaserver/spatial-memory-game:latest
    ports:
      - "1212:1212"
    environment:
      - PORT=1212
      - SCORE_SECRET=whatever
      - DATA_DIR=/app/data
    volumes:
      - ./data:/app/data
